# Generated by Django 4.2.4 on 2023-10-06 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("predict_popularity", "0002_remove_popularity_predictions_duration_and_more"),
        ("accounts", "0002_alter_userprofileinfo_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfileInfo",
        ),
    ]
